// Code generated by MockGen. DO NOT EDIT.
// Source: database/json/interface.go
//
// Generated by this command:
//
//	mockgen -source=database/json/interface.go -destination=mocks/recipes_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	json "github.com/qmajid/daneshkar/database/json"
	gomock "go.uber.org/mock/gomock"
)

// MockIRecipes is a mock of IRecipes interface.
type MockIRecipes struct {
	ctrl     *gomock.Controller
	recorder *MockIRecipesMockRecorder
	isgomock struct{}
}

// MockIRecipesMockRecorder is the mock recorder for MockIRecipes.
type MockIRecipesMockRecorder struct {
	mock *MockIRecipes
}

// NewMockIRecipes creates a new mock instance.
func NewMockIRecipes(ctrl *gomock.Controller) *MockIRecipes {
	mock := &MockIRecipes{ctrl: ctrl}
	mock.recorder = &MockIRecipesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRecipes) EXPECT() *MockIRecipesMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockIRecipes) GetByID(id string) (*json.Recipe, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*json.Recipe)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIRecipesMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIRecipes)(nil).GetByID), id)
}
